name: Generate Report

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to generate a report for."
        required: true

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install @themarkup/blacklight-collector
      
    - name: Set up build
      run: npm run build

    - name: Run Blacklight Collector
      run: |
        node example.js
